In [1]:
# install beautifulsoup for the first time if not there
#!conda install BeautifulSoup4
#!pip install BeautifulSoup4
#!pip install html5lib

In [1]:
import requests
import pandas as pd
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
from IPython.display import display, HTML

In [2]:
html="""<html>
    <head>
        <title>
            This is an example page
        </title>
    </head>
    <body>
        Here is the content of the page
        <p>
            One paragraph
        </p>
        <li> one </li>
        <li> two </li>
        <table>
            <tr>
                <td>col 1</td>
                <td>col 2</td>
            </tr>
            <tr>
                <td>val 1</td>
                <td>val 2</td>
            </tr>
        </table>
        End of body
    </body>
</html>"""

In [3]:
HTML(html)

In [4]:
root = ET.fromstring(html)

In [5]:
for element in root.iter('td'):
    print(element.text)

col 1
col 2
val 1
val 2

In [6]:
messed_html = html + "blablabla"
root = ET.fromstring(messed_html)

ParseError: junk after document element: line 26, column 7 (<string>)

In [7]:
soup = BeautifulSoup(messed_html, 'html')

In [8]:
for element in soup.find_all('td'):
    print(element.text)

col 1
col 2
val 1
val 2

In [9]:
def print_html_tree(tag,level = 0):
    print('\t'*level + tag.name)
    for child in tag.findChildren():
        print_html_tree(child, level+1)

In [10]:
print_html_tree(soup.currentTag)

[document]
	html
		head
			title
		title
		body
			p
			li
			li
			table
				tr
					td
					td
				td
				td
				tr
					td
					td
				td
				td
			tr
				td
				td
			td
			td
			tr
				td
				td
			td
			td
		p
		li
		li
		table
			tr
				td
				td
			td
			td
			tr
				td
				td
			td
			td
		tr
			td
			td
		td
		td
		tr
			td
			td
		td
		td
	head
		title
	title
	body
		p
		li
		li
		table
			tr
				td
				td
			td
			td
			tr
				td
				td
			td
			td
		tr
			td
			td
		td
		td
		tr
			td
			td
		td
		td
	p
	li
	li
	table
		tr
			td
			td
		td
		td
		tr
			td
			td
		td
		td
	tr
		td
		td
	td
	td
	tr
		td
		td
	td
	td
	html

/tmp/ipykernel_68/2094678356.py:3: DeprecationWarning: Call to deprecated method findChildren. (Replaced by find_all) -- Deprecated since version 3.0.0.
  for child in tag.findChildren():

Extract names and titles of [MIS Faulty at UGA](https://www.terry.uga.edu/directory/?group=management-information-systems)

How many assistant professors are there?

In [14]:
r = requests.get("https://www.terry.uga.edu/directory/?group=management-information-systems")

In [15]:
r.status_code # nolonger works

403

In [15]:
### html = r.text

In [19]:
with open("data/mis.html", encoding="utf-8") as f:
    html = '\n'.join(f.readlines())

In [20]:
print(html)

<!doctype html>

<html lang="en-US">

<head>

	<meta charset="UTF-8">

	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="profile" href="https://gmpg.org/xfn/11">





        <script type="text/javascript" data-pressidium-cc-no-block>

            function onPressidiumCookieConsentUpdated(event) {

                window.dataLayer = window.dataLayer || [];

                window.dataLayer.push({

                    event: event.type,

                    consent: event.detail,

                });

            }



            window.addEventListener('pressidium-cookie-consent-accepted', onPressidiumCookieConsentUpdated);

            window.addEventListener('pressidium-cookie-consent-changed', onPressidiumCookieConsentUpdated);

        </script>





        <style id="pressidium-cc-styles">

            .pressidium-cc-theme {

                --cc-bg: #fffafa;

--cc-text: #55111a;

--cc-btn-primary-bg: #ba0c2f;

--cc-btn-primary-text: #fffafa;

--cc-btn-primary-hover-bg: #391d29;

--cc-btn-primary-hover-text: #fffafa;

--cc-btn-secondary-bg: #f9e1e3;

--cc-btn-secondary-text: #55111a;

--cc-btn-secondary-hover-bg: #eac7ca;

--cc-btn-secondary-hover-text: #55111a;

--cc-toggle-bg-off: #d68f99;

--cc-toggle-bg-on: #ba0c2f;

--cc-toggle-bg-readonly: #f1cbd0;

--cc-toggle-knob-bg: #ffffff;

--cc-toggle-knob-icon-color: #faebee;

--cc-cookie-category-block-bg: #f9ebec;

--cc-cookie-category-block-bg-hover: #f9dcdf;

--cc-section-border: #f4f0f1;

--cc-block-text: #55111a;

--cc-cookie-table-border: #f3e2e4;

--cc-overlay-bg: rgba(255, 230, 229, .85);

--cc-webkit-scrollbar-bg: #f9ebec;

--cc-webkit-scrollbar-bg-hover: #222222;

--cc-btn-floating-bg: #ba0c2f;

--cc-btn-floating-icon: #ffffff;

--cc-btn-floating-hover-bg: #000000;

--cc-btn-floating-hover-icon: #ffffff;

            }

        </style>



        <meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />



<!-- Google Tag Manager for WordPress by gtm4wp.com -->

<script data-cfasync="false" data-pagespeed-no-defer>

	var gtm4wp_datalayer_name = "dataLayer";

	var dataLayer = dataLayer || [];

	(function(){dataLayer.push(arguments);})('set', 'developer_id.dNGJiYT', true);

</script>

<!-- End Google Tag Manager for WordPress by gtm4wp.com -->

	<!-- This site is optimized with the Yoast SEO plugin v28.7 - https://yoast.com/product/yoast-seo-wordpress/ -->

	<title>Directory &#8211; Terry College of Business</title>

	<link rel="canonical" href="https://www.terry.uga.edu/group/management-information-systems/" />

	<meta property="og:locale" content="en_US" />

	<meta property="og:type" content="website" />

	<meta property="og:url" content="https://www.terry.uga.edu/group/management-information-systems/" />

	<meta property="og:site_name" content="Terry College of Business" />

	<meta name="twitter:card" content="summary_large_image" />

	<meta name="twitter:site" content="@TerryCollege" />

	<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https:\/\/schema.org","@graph":[{"@type":"CollectionPage","@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/","url":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/","name":"","isPartOf":{"@id":"https:\/\/www.terry.uga.edu\/#website"},"primaryImageOfPage":{"@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/#primaryimage"},"image":{"@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/#primaryimage"},"thumbnailUrl":"https:\/\/www.terry.uga.edu\/wp-content\/uploads\/karen-aguar-2026.jpg","breadcrumb":{"@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/#breadcrumb"},"inLanguage":"en-US"},{"@type":"ImageObject","inLanguage":"en-US","@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/#primaryimage","url":"https:\/\/www.terry.uga.edu\/wp-content\/uploads\/karen-aguar-2026.jpg","contentUrl":"https:\/\/www.terry.uga.edu\/wp-content\/uploads\/karen-aguar-2026.jpg","width":1000,"height":1500,"caption":"Karen Aguar headshot"},{"@type":"BreadcrumbList","@id":"https:\/\/www.terry.uga.edu\/group\/management-information-systems\/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/www.terry.uga.edu\/"},{"@type":"ListItem","position":2,"name":"Faculty & Staff Directory","item":"https:\/\/www.terry.uga.edu\/directory\/"},{"@type":"ListItem","position":3,"name":"Management Information Systems"}]},{"@type":"WebSite","@id":"https:\/\/www.terry.uga.edu\/#website","url":"https:\/\/www.terry.uga.edu\/","name":"Terry College of Business","description":"","publisher":{"@id":"https:\/\/www.terry.uga.edu\/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https:\/\/www.terry.uga.edu\/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https:\/\/www.terry.uga.edu\/#organization","name":"Terry College of Business","url":"https:\/\/www.terry.uga.edu\/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https:\/\/www.terry.uga.edu\/#\/schema\/logo\/image\/","url":"https:\/\/www.terry.uga.edu\/wp-content\/uploads\/Terry_logo_Horizontal_FC.png","contentUrl":"https:\/\/www.terry.uga.edu\/wp-content\/uploads\/Terry_logo_Horizontal_FC.png","width":6729,"height":1655,"caption":"Terry College of Business"},"image":{"@id":"https:\/\/www.terry.uga.edu\/#\/schema\/logo\/image\/"},"sameAs":["https:\/\/www.facebook.com\/terrycollege","https:\/\/x.com\/TerryCollege","https:\/\/www.linkedin.com\/school\/university-of-georgia---terry-college-of-business\/"]}]}</script>

	<!-- / Yoast SEO plugin. -->





<style id="wp-block-library-inline-css">

:root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}:root .has-text-align-center{text-align:center}:root .has-text-align-left{text-align:left}:root .has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{word-wrap:normal!important;border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px;word-break:normal!important}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style^=border-color],[style*=";border-color"],[style*="; border-color"]){border-style:solid}html :where([style^=border-top-color],[style*=";border-top-color"],[style*="; border-top-color"]){border-top-style:solid}html :where([style^=border-right-color],[style*=";border-right-color"],[style*="; border-right-color"]){border-right-style:solid}html :where([style^=border-bottom-color],[style*=";border-bottom-color"],[style*="; border-bottom-color"]){border-bottom-style:solid}html :where([style^=border-left-color],[style*=";border-left-color"],[style*="; border-left-color"]){border-left-style:solid}html :where([style^=border-width],[style*=";border-width"],[style*="; border-width"]){border-style:solid}html :where([style^=border-top-width],[style*=";border-top-width"],[style*="; border-top-width"]){border-top-style:solid}html :where([style^=border-right-width],[style*=";border-right-width"],[style*="; border-right-width"]){border-right-style:solid}html :where([style^=border-bottom-width],[style*=";border-bottom-width"],[style*="; border-bottom-width"]){border-bottom-style:solid}html :where([style^=border-left-width],[style*=";border-left-width"],[style*="; border-left-width"]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}



/*# sourceURL=/wp-includes/css/dist/block-library/common.min.css */

</style>



<style id="global-styles-inline-css">


In [21]:
HTML(html)

In [22]:
root = ET.fromstring(html)

ParseError: syntax error: line 1, column 0 (<string>)

In [23]:
soup = BeautifulSoup(html, 'html')

In [24]:
names = soup.find_all('a', attrs={'class':'entry-title'}, )
names = [name for name in names if name.text != ""]
urls = [name.attrs['href'] for name in names]
names = [name.text for name in names]
len(names)

58

In [25]:
positions = soup.find_all('span', attrs={'class':'position__title'})
len(positions)

62

In [26]:
# lengths of names and postisions do not match, need to find another way

In [27]:
cards = soup.find_all('div', attrs={'class':'col-12 col-sm-8'})
len(cards)

58

In [28]:
people = []
for card in cards:
    name=card.find('a', attrs={'class':                          
                         'entry-title'}).text
    position=card.find('span', attrs={'class':
                         'position__title'}).text
    person = {'name':name, 'position':position}
    people.append(person)
#people
df = pd.DataFrame(people)

In [29]:
df.head()

,name,position
0,Karen Aguar,Senior Lecturer
1,John-Patrick (JP) Akinyemi,Assistant Professor
2,Marie-Claude (Maric) Boudreau,Brown Family Professor of Business Sustainabil...
3,Eunsol Cho,Assistant Professor
4,Chris Colson,Part-Time Lecturer

In [30]:
sum(df.position == 'Assistant Professor')

7

## using pandas read_html

The web page has to have a table

In [31]:
response = requests.get("https://sicemdawgs.com/uga-football-roster/")
response.status_code

200

In [35]:
from io import StringIO

In [36]:
dfs = pd.read_html(StringIO(response.text))

In [37]:
type(dfs)

list

In [38]:
len(dfs)

1

In [39]:
df1 = dfs[0]
df1

,No.,Name,Pos.,Cl.,Ht.,Wt.,Hometown (High School)
0,0,Gabe Harris Jr.,OLB,Sr.,6-4,260,"Thomasville, GA (IMG Academy)"
1,0,Sacovie White-Helton,WR,Jr.,5-9,180,"Cartersville, GA (Cass)"
2,1,Ellis Robinson IV,DB,Jr.,6-0,180,"New Haven, CT (IMG Academy)"
3,1,Talyn Taylor,WR,So.,6-0,190,"Geneva, IL (Geneva)"
4,2,Thomas Blackshear,WR,So.,6-1,200,"Savannah, GA (Calvary Day School)"
...,...,...,...,...,...,...,...
123,96,JJ Hanne,DL,So.,6-4,290,"Berlin, Germany (Santa Margarita Cath.)"
124,97,Wade Register,P,Fr.,6-3,225,"Dublin, GA (Trinity Christian)"
125,98,Connor Ferguson,PK,So.,5-9,155,"Savannah, GA (Benedictine Military)"
126,99,Joseph Jonah-Ajonye,DL,Jr.,6-4,275,"Shenandoah, TX (Oak Ridge)"
127,99,Harran Zureikat,PK,Fr.,6-1,190,"Pittsburgh, PA (Fox Chapel Area)"